# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build datax-core
      run: mvn -B package install --file DataProcessing/datax-core/pom.xml
    - name: Upload datax-core artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: DataProcessing/datax-core/datax-core_2.4_2.11-*-SNAPSHOT.jar
    - name: Build datax-keyvault
      run: mvn -B package install --file DataProcessing/datax-keyvault/pom.xml
    - name: Build datax-utility
      run: mvn -B package install --file DataProcessing/datax-utility/pom.xml
    - name: Build datax-host
      run: mvn -B package install --file DataProcessing/datax-host/pom.xml
    - name: Build datax-udf-samples
      run: mvn -B package install --file DataProcessing/datax-udf-samples/pom.xml
    
