# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build datax-core
      run: mvn -B package install --file DataProcessing/datax-core/pom.xml
    - name: Upload datax-core artifact
      uses: actions/upload-artifact@v3
      with:
        name: datax-core
        path: DataProcessing/datax-core/target/datax-core_2.4_2.11-*-SNAPSHOT*.jar
        if-no-files-found: error 
    - name: Build datax-keyvault
      run: mvn -B package install --file DataProcessing/datax-keyvault/pom.xml
    - name: Upload datax-keyvault artifact
      uses: actions/upload-artifact@v3
      with:
        name: datax-keyvault
        path: DataProcessing/datax-keyvault/target/datax-keyvault_2.4_2.11-*-SNAPSHOT*.jar
    - name: Build datax-utility
      run: mvn -B package install --file DataProcessing/datax-utility/pom.xml
    - name: Upload datax-utility artifact
      uses: actions/upload-artifact@v3
      with:
        name: datax-utility
        path: DataProcessing/datax-utility/target/datax-utility_2.4_2.11-*-SNAPSHOT*.jar
    - name: Build datax-host
      run: mvn -B package install --file DataProcessing/datax-host/pom.xml
    - name: Upload datax-host artifact
      uses: actions/upload-artifact@v3
      with:
        name: datax-host
        path: DataProcessing/datax-host/target/datax-host_2.4_2.11-*-SNAPSHOT*.jar
    - name: Build datax-udf-samples
      run: mvn -B package install --file DataProcessing/datax-udf-samples/pom.xml
    - name: Upload datax-udf-samples
      uses: actions/upload-artifact@v3
      with:
        name: datax-udf-samples
        path: DataProcessing/datax-udf-samples/target/datax-udf-samples_2.4_2.11-*-SNAPSHOT*.jar
        if-no-files-found: error 
    
